-- Setting it here somehow does not work, I really should try to understand lua
-- vim.g.indent_blankline_filetype_exclude = {"terminal"}
-- vim.g.indent_blankline_filetype_exclude = { 'help' }
-- vim.g.indent_blankline_buftype_exclude = { 'terminal', 'nofile', 'packer'}
