-- require("transparent").setup({
--   enable = true, -- boolean: enable transparent
--   groups = {
--     "Normal", "Comment", "Constant", "Special", "Identifier", "Statement", "PreProc", "Type",
--     "Underlined", "Todo", "String", "Function", "Conditional", "Repeat", "Operator", "Structure",
--     "LineNr", -- "NonText",
--     "SignColumn", "CursorLineNr", "EndOfBuffer", "NvimTree", "NvimTreeNormal", "NvimTreeRootFolder",
--     "NvimTreeSpecialFile", "CursorLine"
--   },
--   extra_groups = { -- table/string: additional groups that should be clear
--     -- "all"
--     -- example of akinsho/nvim-bufferline.lua
--     "BufferLineTabClose", "BufferlineBufferSelected", "BufferLineFill", "BufferLineBackground",
--     "BufferLineSeparator", "BufferLineIndicatorSelected"
--
--   },
--   --
--   exclude = {} -- table: groups you don't want to clear
--
-- })
--
