theme = "ingrid"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

# [keys.insert]
# j = { j = "normal_mode" } # Maps `jj`

[keys.normal]
"A-1" = "copy_selection_on_prev_line" 
space = {t = ":toggle lsp.display-inlay-hints"}

[editor.indent-guides]
render = true
